In [ ]:
import numpy as np


# define Python user-defined exceptions
class ValueError(Exception):
  "List must contain nine numbers."
  pass


def calculate(list):
  if len(list) < 9:
    raise ValueError

  np_list = np.array(list).reshape((3, 3))

  calculations = {
    'mean': [np_list.mean(axis=0),
             np_list.mean(axis=1),
             np_list.mean()],
    'variance': [np_list.var(axis=0),
                 np_list.var(axis=1),
                 np_list.var()],
    'standard deviation':
    [np_list.std(axis=0),
     np_list.std(axis=1),
     np_list.std()],
    'max': [np_list.max(axis=0),
            np_list.max(axis=1),
            np_list.max()],
    'min': [np_list.min(axis=0),
            np_list.min(axis=1),
            np_list.min()],
    'sum': [np_list.sum(axis=0),
            np_list.sum(axis=1),
            np_list.sum()]
  }

  return calculations


In [ ]:
list = [0,9,2,4,3,1,7,5,6]

In [ ]:
calculate(list)

{'mean': [array([3.66666667, 5.66666667, 3.        ]),
  array([3.66666667, 2.66666667, 6.        ]),
  4.111111111111111],
 'variance': [array([8.22222222, 6.22222222, 4.66666667]),
  array([14.88888889,  1.55555556,  0.66666667]),
  7.65432098765432],
 'standard deviation': [array([2.86744176, 2.49443826, 2.1602469 ]),
  array([3.8586123 , 1.24721913, 0.81649658]),
  2.7666443551086073],
 'max': [array([7, 9, 6]), array([9, 4, 7]), 9],
 'min': [array([0, 3, 1]), array([0, 1, 5]), 0],
 'sum': [array([11, 17,  9]), array([11,  8, 18]), 37]}